name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo make prepare

    - name: Build PDF from Tex-source 
      run: make

    - name: Build PDF from Markdown
      run: make markdown

    - name: Store result PDF
      uses: actions/upload-artifact@v3
      with:
        name: pdf-result
        path: |
          test.pdf
          Gxsm-3.0-Manual.pdf

    - name: Publish docs
      run: mkdocs gh-deploy --force

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: test.pdf
        asset_name: test.pdf
        asset_content_type: application/pdf

