name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo make prepare

    - name: Build PDF from Tex-source
      run: make 

    - name: Build PDF from Markdown-source
      run: pushd markdown && make && make pages && popd

    - name: Where are we now
      run: pwd && ls && ls src && ls markdown

    - name: Publish docs
      run: pushd markdown/mkdocs && mkdocs gh-deploy && popd

    - name: Store result PDF
      uses: actions/upload-artifact@v3
      with:
        name: pdf-result
        path: markdown/test.pdf src/*.pdf

